### ISSUE TITLE
http-server fork.

### ISSUE THREAD

**Issue by Swampy821** [Swampy821/spriteChat#6]
It'd be nice if the server forked a process to host the front end of the code. Preferably through Hapi.js instead of requiring an administrator to use an outside host.

**Comment by varatep** [comment]
Expressjs to serve the front end?

**Comment by Swampy821** [comment]
I'd much rather use Hapi.js. It's a lot easier to use and a bit more structured.

**Comment by Swampy821** [comment]
Completed!
